<?php
/*
类名：WebQzeon
描述：QQ空间嵌入web页
*/
class WebQzeonAction extends FrontAction{
	public function index()
	{		
		$cat_id=Input::getVar($_REQUEST['cat_id']);
		if(!empty($cat_id))
		{
			$cat_ids=M("goods_cat")->where("cat_id='".$cat_id."'")->field("goods_id")->select();
			$ids='';
			foreach($cat_ids as $c)
			{
				if($ids=='')
				{
					$ids=$c['goods_id'];
				}
				else
				{
					$ids.=",".$c['goods_id'];
				}
			}
			$map['goods_id']=array("in",$ids);
			$url .= 'cat_id_' . $cat_id;
			$this->title($cat_id);
		}
		else
		{
			$url.="cat_id_0";
			$this->title();
		}
		$m=D('Index');
		//标签
		$cat_list=$m->cat_list();
		$this->assign("cat_list",$cat_list);
		$goods=M("goods");
		$goods_list=$this->_list($goods,$map,15,$url,"sort",false);
		foreach($goods_list as $key=>$val)
		{
			if($val['goods_promotion']>0)//判断是否有促销价格
			{
				if($val['promotion_starttime']<time() && $val['promotion_endtime']>time())
				{
					$price=explode('.',$val['goods_promotion']);
					$goods_list[$key]['price_integer']=$price[0];
					$goods_list[$key]['price_decimal']=$price[1];	
				}
				else
				{
					$price=explode('.',$val['goods_price']);
					$goods_list[$key]['price_integer']=$price[0];
					$goods_list[$key]['price_decimal']=$price[1];	
				}
			}
			else
			{
				$price=explode('.',$val['goods_price']);
				$goods_list[$key]['price_integer']=$price[0];
				$goods_list[$key]['price_decimal']=$price[1];
			}
			if($val['goods_recommend'])
			{
				$goods_list[$key]['goods_recommend_list']=explode("\r\n",$val['goods_recommend']);
			}
		}
		$this->assign("goods_list",$goods_list);
		$this->display();
    }	
}
?>